name: Release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'Release semantic version (1.2.3-rc.4)'
        required: true
        type: string
      winver:
        description: 'Release windows version (1.2.3.4)'
        required: true
        type: string
      publish:
        description: 'Release Type'
        required: true
        default: 'release'
        type: choice
        options:
        - none
        - release

jobs:
  build:
    name: Build Artifacts
    uses: ./.github/workflows/build.yaml
    with:
      semver: ${{ github.event.inputs.semver }}
      winver: ${{ github.event.inputs.winver }}

  release:
    name: Release Artifacts
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest
    
    needs: job1

    steps:
    
    - uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: Assemble
      shell: bash
      run: >
        mkdir -p dist/net6.0
        mkdir -p dist/net8.0
        
        cp build-artifacts/net6.0/*.* dist/net6.0
        cp build-artifacts/net8.0/*.* dist/net8.0
        
        zip -r DotnetToolWrapper.zip dist

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts-release
        path: |
          dist/DotnetToolWrapper.zip

    - name: Create release
      if: ${{ inputs.publish == 'release' }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/DotnetToolWrapper.zip,dist/_manifest/spdx_2.2/*.*"
        generateReleaseNotes: true
        tag: ${{ github.event.inputs.semver }}
